version: '2'

services:
  elasticsearch:
    restart: always
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - nlog-poc
  nlog-es:
    restart: always
    build: .
    ports:
      - "5000:5000"
    networks:
      - nlog-poc
    depends_on:
      - elasticsearch
  kibana:
    restart: always
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - nlog-poc
    depends_on:
      - elasticsearch

networks:
  nlog-poc:
    driver: bridge
