version: '2'

services:
  mysql:
    restart: always
    build: mysql/
    volumes:
      - ./mysql/data:/var/lib/mysql/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    networks:
      - nlog-poc
  elasticsearch:
    restart: always
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - nlog-poc
  nlog-es:
    restart: always
    build: .
    ports:
      - "5000:5000"
    networks:
      - nlog-poc
    depends_on:
      - mysql
      - elasticsearch
  kibana:
    restart: always
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - nlog-poc
    depends_on:
      - elasticsearch

networks:
  nlog-poc:
    driver: bridge
